# wrangler.toml - Worker configuration
name = "contactworker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "talktech-db"
database_id = "605da4e8-9f81-4560-b9dd-e47d590ba221"  # You'll get this after creating the database

# Environment variables (secrets should be added via CLI, not here)
[vars]
# Non-secret variables can go here
ENVIRONMENT = "production"

# Development settings
[dev]
port = 8787
local_protocol = "http"